"""Build 8.9b's subject: a real, running, OWNED Vanilla install that is expendable.

**This is SETUP, not a clause.** Nothing here is evidence of anything the box
claims; it exists so the destructive steps have something to destroy that is not
`~/vanilla-75b`, which four earlier gates still depend on and which nobody has
an hour of compile time to rebuild.

`pyplan/8.9b-gate-plan.md` G1 asks for "a throwaway Vanilla install made by
Yu'lon's own installer" and calls it the long pole of this box: on this tree an
install press clones, compiles, extracts a 2.4 GB client and builds mmaps, and
the owner's standing rule is that he starts rebuilds, not a lane. So the subject
here is a CLONE of the finished install, moved to a new folder and given its own
identity through the app's own code:

* `composegen.install_id()` is a digest of the ABSOLUTE PATH, so a copy at a new
  path is a different install id, a different compose project, a different
  volume name and a different image tag. That is what makes it a separate
  install rather than a second handle on the gated one — and it is also why the
  claim file has to be rewritten: a copied `.yulon-install.json` names the
  ORIGINAL's id and reads as `UNKNOWN`, which is 8.9a step 4's refusal and not a
  usable subject.
* the compose files are regenerated by `stage_generate_compose`, the shipped
  stage body, so the project name in them is this folder's.
* the built image is RETAGGED to the clone's ref rather than compiled. The image
  is byte-identical either way; what a compile would add is an hour.
* the database volume is created and filled from the original's, so the clone
  has real characters in it. `docker volume` has no copy verb; the copy is a
  `cp -a` inside a throwaway container, which is the documented way.

**What that means for what this gate can claim.** Every object the purge acts on
is genuine — a real folder with a real checkout and a real 2.4 GB `data/`, a real
project, a real volume with real rows, a real built image, a real network, a real
record in `state.json`. What is NOT genuine is the provenance of the bytes: they
were copied rather than produced by a press. Where that matters is said in the
README, in the step it matters in, rather than left for a reader to notice.

Container names are GLOBAL on this tree (`vanilla-db`, `vanilla-realmd`,
`vanilla-mangosd` come from `catalog.json`), so the clone and the original can
never run at the same time. This script takes the original's containers down
first — keeping its volume and its image — and `teardown89b.py` puts them back.

Usage:  ~/gate81b-venv/bin/python setup89b.py
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

GAME = "wow-vanilla"
ORIGINAL = Path.home() / "vanilla-75b"
CLONE = Path.home() / "gate89b" / "server"
STATE_FILE = ".yulon-install.json"


def say(message: str) -> None:
    print(f"[{time.strftime('%H:%M:%SZ', time.gmtime())}] {message}", flush=True)


def sh(*args: str, check: bool = True) -> str:
    done = subprocess.run(args, capture_output=True, text=True, check=False)
    if check and done.returncode != 0:
        raise SystemExit(f"{' '.join(args)} exited {done.returncode}: {done.stderr.strip()}")
    return done.stdout.strip()


def main() -> None:
    from yulon.catalog import composegen, native
    from yulon.catalog.catalog import load_catalog
    from yulon.catalog.installer import installer_for

    entry = load_catalog().get(GAME)
    installer = installer_for(entry)

    original_id = composegen.install_id(ORIGINAL)
    original_project = composegen.project_name(GAME, ORIGINAL)
    say(f"original: {ORIGINAL} id={original_id} project={original_project}")

    # 1. Free the global container names, keeping the original's volume and image.
    say("taking the original's containers down (volumes and images untouched)")
    sh("docker", "compose", "-f", str(ORIGINAL / "docker-compose.yml"),
       "-f", str(ORIGINAL / "docker-compose.override.yml"), "down", check=False)
    say(f"containers now: {sh('docker', 'ps', '-a', '--format', '{{.Names}}') or '(none)'}")

    # 2. The folder.
    if CLONE.exists():
        raise SystemExit(f"{CLONE} already exists; remove it or pick another path")
    CLONE.parent.mkdir(parents=True, exist_ok=True)
    say(f"copying {ORIGINAL} -> {CLONE} (2.8 GB)")
    shutil.copytree(ORIGINAL, CLONE, symlinks=True)
    say(f"copied: {sh('du', '-sh', str(CLONE))}")

    clone_id = composegen.install_id(CLONE)
    clone_project = composegen.project_name(GAME, CLONE)
    say(f"clone:    {CLONE} id={clone_id} project={clone_project}")
    assert clone_id != original_id, "the two folders hash the same; the whole plan depends on this"

    # 3. Its own claim. The copied one names the original's id and reads UNKNOWN.
    copied = json.loads((CLONE / STATE_FILE).read_text(encoding="utf-8"))
    say(f"the copied claim names install_id={copied['install_id']} (the original's)")
    state = native.InstallState(
        game_id=GAME,
        install_id=clone_id,
        family=copied.get("family", "cmangos"),
        # `generate-compose` deliberately dropped: the copied compose carries the
        # ORIGINAL's project name, and leaving the stage recorded would let this
        # clone address the gated install's volume.
        completed=tuple(s for s in copied.get("completed", ()) if s != "generate-compose"),
        updated_unix=int(time.time()),
    )
    native.write_state(CLONE, state)
    say(f"claim rewritten: completed={state.completed}")

    # 4. Retag the built image rather than compiling it again.
    (source_ref,) = composegen.built_image_refs(entry, ORIGINAL)
    (clone_ref,) = composegen.built_image_refs(entry, CLONE)
    say(f"retagging {source_ref} -> {clone_ref}")
    sh("docker", "tag", source_ref, clone_ref)

    # 5. The compose files, through the shipped stage body.
    ctx = native.StageContext(
        server_dir=CLONE,
        client_dir=None,
        state=native.read_state(CLONE, valid=[s.name for s in installer.stages()])
        or state,
        cancel=None,
        secrets=installer.resolve_secrets(CLONE),
    )
    for line in installer.stage_generate_compose(ctx):
        say(f"  | {line}")
    name_line = [
        line
        for line in (CLONE / "docker-compose.yml").read_text(encoding="utf-8").splitlines()
        if line.startswith("name:")
    ]
    say(f"the clone's compose says {name_line}")
    assert clone_project in name_line[0], name_line

    # 6. The database volume, filled from the original's.
    source_volume = f"{original_project}_db-data"
    clone_volume = f"{clone_project}_db-data"
    say(f"creating {clone_volume} and copying {source_volume} into it")
    sh("docker", "volume", "create", clone_volume)
    sh("docker", "run", "--rm",
       "-v", f"{source_volume}:/from:ro", "-v", f"{clone_volume}:/to",
       "alpine:3.20", "sh", "-c", "cp -a /from/. /to/")
    say(f"copied: {sh('docker', 'volume', 'inspect', '--format', '{{.Name}}', clone_volume)}")

    # 7. Up, and let it reach its ready marker.
    say("starting the clone")
    sh("docker", "compose", "-f", str(CLONE / "docker-compose.yml"),
       "-f", str(CLONE / "docker-compose.override.yml"), "up", "-d")
    mark = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(time.time() - 5))
    deadline = time.time() + 1800
    while time.time() < deadline:
        if "Avg Diff:" in sh("docker", "logs", "--since", mark, "vanilla-mangosd", check=False):
            say("the clone reached `Avg Diff:` -- it is a real running server")
            break
        time.sleep(5)
    else:
        raise SystemExit("the clone did not come up")
    say(sh("docker", "ps", "--format", "{{.Names}} {{.Status}}"))

    # 8. Register it with the app, so `state.json` names it and the tab exists.
    from yulon import state as app_state

    loaded = app_state.load_state()
    loaded.remember(app_state.KnownInstall(game=GAME, server_dir=CLONE))
    app_state.save_state(loaded)
    say(f"remembered in state.json: {[str(i.server_dir) for i in loaded.installs]}")

    say("SETUP DONE")


if __name__ == "__main__":
    sys.exit(main())
