"""Compose generation for the native install engine (roadmap 6.2).

One job: turn a catalog entry plus an install identity into the exact text of
three compose files and the keys that belong in `.env`. Pure functions, no
subprocess and no daemon, so the output can be asserted byte for byte — which
matters more here than anywhere else in the engine, because the first thing
that reports a wrong compose file is a build three hours later.

The *content* is template data under `catalog/installers/<game>/native/`
(style-guide §3), never a Python conditional. This module owns the identity,
the substitution, the refusal of anything that cannot be safely spliced, and
the merge into `.env`.

Why three files, restated where the code is:

* `docker-compose.yml` — `name:`, services, container names, image refs, ALL
  ports, binds, volumes, depends_on, healthchecks.
* `docker-compose.override.yml` — runtime `AC_*` env and the `./modules`
  mount, nothing structural: it is auto-loaded and it is rewritten by whatever
  settings surface comes next, whose YAML writer keeps only what it
  understands.
* `docker-compose.build.yml` — `build:` blocks only, never auto-loaded, so a
  post-install `up` cannot start a multi-hour rebuild.

**`ports:` appears in exactly one of them.** Compose CONCATENATES `ports:`
across files: a port "overridden" in the override publishes a second binding
rather than replacing the first. `test_composegen.py` asserts the rendered
override and build files carry no `ports:` key at any depth, and that test is
the only thing standing between a future edit and a stack that binds 3724
twice.
"""

from __future__ import annotations

import hashlib
import os
import posixpath
import re
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from yulon import platform, tuning
from yulon.catalog.catalog import CatalogEntry, NativeInstall
from yulon.log import get_logger

logger = get_logger(__name__)

BASE_FILE = "docker-compose.yml"
OVERRIDE_FILE = "docker-compose.override.yml"
BUILD_FILE = "docker-compose.build.yml"
DOTENV_FILE = ".env"

COMPOSE_FILES: tuple[str, ...] = (BASE_FILE, OVERRIDE_FILE, BUILD_FILE)
"""The `-f` set for every build, in order. See `docker.build_staged()`."""

GENERATED_MARKER = "# generated by Yu'lon"
"""First-line marker every generated file carries, and the whole of the rewrite rule.

`generate-compose` rewrites a file whose first line `is_marker_line()` recognises as this
one, and refuses to touch one whose first line does not. The incident it exists for is
in `rust-prior-art.md` §1: a state file dropped into a directory made the generator
overwrite a real server's compose file and orphan its character volumes. A marker means
the engine can only ever destroy its own work -- which held only up to the byte T25
found: `startswith(GENERATED_MARKER)` answered OURS for ANYTHING glued after the words,
so a user's own `# generated by Yu'lon-custom` (a file they took over, marked in their
own hand) read back as ours and was replaced whole on the next rebuild.
"""

INSTALL_ID_LENGTH = 8
"""Hex digits of the path hash that name an install. 8 is what `docker ps` can show.

A collision would give two installs one compose project — the bug this exists
to prevent — so the length is a real trade. 32 bits over the handful of
directories one person installs to is a birthday probability under 1e-8, and
the state file's own `install_id` check catches the pathological case at
install time rather than letting it run.
"""

# Runtime env the generated override starts with. Two keys, both load-bearing:
# without the first the one-shot never creates the playerbots schema, and
# without the second the bots never log in.
#
# The Linux installer's own override also pins AC_AI_PLAYERBOT_MIN/MAX_RANDOM_
# BOTS to 500/500, and this comment used to argue at length that they should
# stay out. They did not stay out — the compose diff against the proven install
# (2026-08-24) found that a native install would otherwise take mod-playerbots'
# defaults and hand the same user a different world from the same button, and
# they now ship in `catalog.json`'s `install.native.azerothcore.world_env`. Corrected after
# a sweep found this text still arguing the opposite of what the code does.
#
# The argument was not wrong, only outranked, and the part still worth keeping
# is the cost: an env key SHADOWS the matching row in playerbots.conf, so a
# settings surface that edits that file will appear to do nothing until this
# key is removed. Nor is rewriting the env itself immediate — a container that
# is already running keeps the population it started with until it is
# RECREATED, so anything that changes this number is changing what the next
# `up` builds, not what the world outside the window is doing. That is why the
# numbers are DATA in `catalog.json` and not a constant here — a per-game value
# a person may want different, style-guide §3. What is still unmeasured is
# whether 500 bots fits the laptop this path's preflight exists for; the first
# live gate owes an RSS reading at that population, and until it has one the
# number is decided, not earned.
DEFAULT_WORLD_ENV: Mapping[str, str] = {
    "AC_PLAYERBOTS_UPDATES_ENABLE_DATABASES": "1",
    "AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN": "1",
}
"""Settings that are structural rather than tunable: without them the stack is wrong, not merely
different. Anything a person might reasonably want a different value for belongs in
`catalog.json`'s `install.native.azerothcore.world_env` instead — the playerbot population
started here and was moved there after an adversarial review pointed out that a per-game number
in a module constant is exactly what style-guide §3 forbids, and that one machine's bot
population is not a default for every machine.

The environment differences the compose diff turned up and this deliberately does NOT carry —
`AC_CCACHE`, `CTYPE`, `CSCRIPTS`, `DATAPATH`, `USER_CONF_PATH` and the three empty
`AC_RESTARTER_*` — are build-time settings upstream's compose file keeps on the runtime services
too. The image's `entrypoint.sh` reads none of them: it uses `CONF_DIR`, `LOGS_DIR` and
`ACORE_COMPONENT`, and the image sets `ACORE_COMPONENT` itself. Checked in the image, not assumed.
"""


def env_name_for(ini_key: str) -> str:
    """The environment variable AzerothCore reads a given ini key from.

    `"AC_" + upper_snake(key)`, and the transform is MEASURED rather than
    guessed: `Config.cpp:435-438` builds the name, `:370-374` documents the
    case rule with three examples (`SomeConfig => SOME_CONFIG`,
    `myNestedConfig.opt1 => MY_NESTED_CONFIG_OPT_1`,
    `LogDB.Opt.ClearTime => LOG_DB_OPT_CLEAR_TIME`) and `:391-394` is the
    separator rule -- `.`, `-` and a space each become `_`. The whole read is
    `.notes/phase8-reads/azerothcore.md`.

    It matters that this is the REAL rule and not a plausible one. The obvious
    guess -- uppercase and turn dots into underscores -- gives
    `AC_AIPLAYERBOT_MINRANDOMBOTS`, which is neither what this app writes into
    the override nor what the server looks for, and a settings surface built on
    it would find no shadowed key anywhere and warn about none.

    Generic rather than per-key, which is the point: the catalog has relied on
    it for `AiPlayerbot.MinRandomBots` since the bot population moved into
    `catalog.json`, and `test_the_transform_agrees_with_every_env_name_this_
    app_actually_writes` pins all four names this app really writes against it.
    """
    out: list[str] = []
    previous = ""
    for char in ini_key:
        if char in " .-":
            out.append("_")
            previous = ""
            continue
        boundary = previous and (
            (previous.islower() and char.isupper())
            or (previous.isalpha() and char.isdigit())
            or (previous.isdigit() and char.isalpha())
        )
        if boundary:
            out.append("_")
        out.append(char.upper())
        previous = char
    return "AC_" + "".join(out)


def world_env(entry: CatalogEntry, override: Mapping[str, str] | None = None) -> dict[str, str]:
    """The runtime environment this install's generated override carries.

    One function for the question, asked by the generator when it WRITES the
    file and by the Tuning tab when it warns that a key is shadowed (T44 round
    2). Two spellings of it would be two answers, and the tab's whole job there
    is to say what the file says.

    The `else {}` for a family with no `azerothcore` block is the honest
    default: a CMaNGOS server is configured through its `.conf` files and not
    through container environment.
    """
    native_install = entry.install.native
    entry_env = (
        native_install.azerothcore.world_env
        if native_install is not None and native_install.azerothcore is not None
        else {}
    )
    if override is not None:
        return dict(override)
    return {**DEFAULT_WORLD_ENV, **entry_env}


_world_env = world_env
"""A private alias, so the generator can call this while its own parameter of
that name is in scope. One function, two spellings of the reference."""


CHANNEL_BACKUP_SUFFIX = ".before-channel"
"""The override as it was before the command channel's first press, kept beside it.

`channel_setup.BACKUP_SUFFIX` is this constant. It lives here because the
channel's state is read by every writer of the override, and the install
stages in `native.py` cannot import `channel_setup`.
"""

CHANNEL_PORT_VAR = "DOCKER_SOAP_EXTERNAL_PORT"
"""The `.env` key the channel claims its host port under (`channel_setup.HOST_PORT_VAR`)."""

CHANNEL_PORT_RELEASED = "127.0.0.1:0"
"""What a rollback writes there, on both of its arms (`channel_setup.RELEASED_HOST_PORT`)."""


def channel_is_on(server_dir: Path) -> bool:
    """Whether this install's command-channel press is live.

    Two records, both the channel's own. `channel_setup.enable()` writes
    `<override>.before-channel` on the FIRST press and only a complete
    `roll_back()` deletes it, so the file is the record that a press stands.
    But a rollback that finds the override edited since the press releases the
    port and KEEPS that file (and one interrupted before its last step keeps
    it too), and both arms write the released claim first. So a released claim
    is a rollback the user pressed, and the backup beside it is not a live
    press. Measured on yulon-ubuntu 2026-09-24 (T101): without this, the next
    Repair would have switched the channel's environment back on.
    """
    if not (server_dir / f"{OVERRIDE_FILE}{CHANNEL_BACKUP_SUFFIX}").is_file():
        return False
    return dotenv_value(server_dir, CHANNEL_PORT_VAR) != CHANNEL_PORT_RELEASED


def channel_world_env(entry: CatalogEntry, server_dir: Path) -> dict[str, str] | None:
    """The environment a REGENERATED override carries: `None` unless a channel press is live.

    `None` is `render()`'s own default, the install's environment. While the
    press is live it is that environment plus the channel's Enable
    (`operations.enable_env`), merged as `channel_setup.enable()` merges it, so
    the file is the one the press wrote. Every writer that regenerates the
    override asks this: the install's `generate-compose` stage (a first
    install, a Repair, and Update to latest's put-back) and the T94 reset. Until
    T101 the stage rendered without it, so a Repair on WotLK wrote the
    pre-channel override back and its own `up` brought the world up with SOAP
    off (yulon-ubuntu, 2026-09-24).

    A channel switched on through `enable_conf` (the CMaNGOS trees) has nothing
    here: its keys are in `mangosd.conf`, which no regeneration rewrites.
    """
    operations = entry.operations
    if operations is None or not operations.enable_env or not channel_is_on(server_dir):
        return None
    return {**world_env(entry), **operations.enable_env}


def shadowed_by_env(text: str, env: Mapping[str, str]) -> tuple[tuple[str, str], ...]:
    """Which of this conf's keys the container environment overrides, and by what.

    `(ini key, environment variable)` per shadowed key, in the file's own
    order. `Config.cpp:540-552`: the environment wins over both the file value
    and the compiled default, so a key with an env row behind it can be edited
    in the conf all day and the world will go on reading the row.

    The remedy for such a key is NOT a container recreate on its own: the
    override is regenerated from the same data, so a recreate re-applies the
    same value. The env row has to change or go first. That sentence is the
    Tuning tab's, and this function is what tells it which files it applies to.
    """
    return tuple(
        (key, name) for key in tuning.conf_keys(text) if (name := env_name_for(key)) in env
    )


# Characters that cannot be spliced into the templates safely, whatever the
# escaping. A scalar here lands in TWO contexts at once — a bare YAML value
# (`MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-<pw>}`) and a quoted, semicolon-
# separated one (`"ac-database;3306;root;<pw>;acore_auth"`) — and compose's own
# interpolation runs on top of both after YAML has already unescaped them. `#`
# truncates at a comment, `}` ends the `:-` default early, `;` splits the
# database field list, `"`/`\` break the quoted string, `$` opens another
# interpolation, and a newline splices arbitrary YAML. No single escaping
# survives all six, so a bad value is REFUSED: this is an install-time option
# and the user can pick another password.
_UNSAFE_SCALAR_CHARS = frozenset("$\"\\;#{}\r\n\t'")


class ComposeGenError(RuntimeError):
    """A compose file could not be generated (message is user-readable)."""


def install_id(server_dir: Path, *, platform_id: Callable[[], str] = platform.detect) -> str:
    """Short, stable id for one install, derived from where it lives.

    SHA-256 of the ABSOLUTE path, first `INSTALL_ID_LENGTH` hex digits. Three
    normalisations, each because two spellings of one directory must not become
    two stacks: the path is made absolute, back-slashes become forward slashes,
    and a trailing separator is dropped. On Windows it is also lowercased,
    because NTFS is case-insensitive and `C:\\Games\\wow` and `c:\\games\\wow`
    are the same folder.

    This is the value the compose project name carries and the value the state
    file records, which is what makes a COPIED install directory refusable:
    the copy's path hashes differently from the `install_id` its state file
    carries, so a resume in it is refused instead of adopting the original's
    containers and volumes.
    """
    return hashlib.sha256(_identity_key(server_dir, platform_id).encode()).hexdigest()[
        :INSTALL_ID_LENGTH
    ]


def _identity_key(server_dir: Path, platform_id: Callable[[], str]) -> str:
    # A folder inside a WSL distro is the folder the distro names (T125). Yu'lon
    # built it there, on Linux, and recorded the id of `/home/...`; the Windows
    # app holds the same folder as `\\wsl.localhost\<distro>\...`, and hashing
    # THAT spelling (lowercased, as a Windows path) named another image tag for
    # the same install -- measured on yulon-win11: `2f1c23d4` recorded,
    # `27a96c15` recomputed. The distro's filesystem is case-sensitive, so the
    # Linux spelling is taken as it is.
    inside = platform.wsl_linux_path(server_dir)
    if inside is not None:
        return posixpath.normpath(inside)
    text = str(Path(os.path.abspath(server_dir))).replace("\\", "/")
    while len(text) > 1 and text.endswith("/"):
        text = text[:-1]
    return text.lower() if platform_id() == "windows" else text


PROJECT_PREFIX = "yulon-"
"""Every compose project this app makes starts with this, and nothing else's does.

The one place the literal is spelled. `native._refuse_foreign_containers()`
reads it too, to tell a container that belongs to another install THIS app
made from one that belongs to a stranger's Docker Compose project — a
distinction a hand-typed second copy of `"yulon-"` could quietly drift from.
"""


def project_name(
    game_id: str, server_dir: Path, *, platform_id: Callable[[], str] = platform.detect
) -> str:
    """This install's compose project: `yulon-<game>-<install id>`.

    Written into the base file's `name:`, which retires the `.env` pin on the
    native path entirely — `docker.compose_project_name()` already reads `name:`
    out of the files, so a moved folder keeps working because the identity
    travels inside it.

    Per-install rather than per-game because compose keys named VOLUMES by
    project too: two installs of one game under one project name would share a
    database volume, and the second `up` would mount the first's characters.
    """
    return f"{PROJECT_PREFIX}{_slug(game_id)}-{install_id(server_dir, platform_id=platform_id)}"


def built_image_refs(
    entry: CatalogEntry, server_dir: Path, *, platform_id: Callable[[], str] = platform.detect
) -> tuple[str, ...]:
    """The image references this install's build produces, fully qualified.

    Needed because "has this been built?" cannot be asked of compose. Measured
    on yulon-ubuntu (Docker 29.1.3, Compose 2.40.3, 2026-08-24): after a
    successful `compose -f… build`, `compose images -q` returns **nothing** —
    both bare and with the same `-f` set — and only starts answering once
    containers exist (`compose create` is enough; `up` is not required). Compose
    enumerates the images of a project's CREATED CONTAINERS, not of its service
    definitions, exactly as `images_built()`'s docstring feared.

    That window — built, no containers yet — is the whole window a resume asks
    in, so the old question answered "not built" for every finished build and a
    resume re-ran the compile. Cheap in BuildKit cache terms and still wrong:
    the engine would have reported hours of work it did not need to do.

    The prefix and the service keys are the entry's (`install.native.images`,
    `.image_prefix`) since 7.1, so two games cannot tag into one namespace.
    """
    native = _native_of(entry)
    tag = image_tag(server_dir, platform_id=platform_id)
    return tuple(f"{native.image_prefix}{name}:{tag}" for name in native.images)


def _native_of(entry: CatalogEntry) -> NativeInstall:
    """The entry's native block, or the one refusal every native-only function shares."""
    if entry.install.native is None:
        raise ComposeGenError(
            f"{entry.name} does not say how to install natively (no `install.native` in "
            "catalog.json), so no compose files were generated."
        )
    return entry.install.native


def image_tag(server_dir: Path, *, platform_id: Callable[[], str] = platform.detect) -> str:
    """Default tag for images built for this install, so two builds cannot overwrite each other."""
    return f"native-{install_id(server_dir, platform_id=platform_id)}"


def _slug(text: str) -> str:
    """Lowercase `[a-z0-9_-]`, so the project name is legal and readable in `docker ps`."""
    out: list[str] = []
    for char in text.lower():
        if char.isascii() and (char.isalnum() or char in "-_"):
            out.append(char)
        elif out and out[-1] != "-":
            out.append("-")
    return "".join(out).strip("-_") or "game"


@dataclass(frozen=True)
class ComposePlan:
    """The three files' text plus the `.env` keys this install needs on top of them.

    `dotenv` is empty for a fixed-password game (WotLK): the catalog's value is
    the base file's interpolation default and needs no `.env`. For a
    generated-password game it carries exactly `DB_ROOT_PASSWORD`, which
    `write_plan()` merges into `.env` through `write_dotenv()` — the one writer
    of that file — so the secret is never in a compose file git can see. A
    docstring here once promised the second behaviour while nothing implemented
    it (review, 2026-08-23); it has had a caller since 7.1.
    """

    base: str
    override: str
    build: str
    dotenv: Mapping[str, str]


def container_user(platform_id: Callable[[], str] = platform.detect) -> str:
    """The `user:` line for the services that write to the bound-out env/dist.

    On Windows this is `user: "0:0"`, and it is not a convenience. Docker
    Desktop mounts a Windows drive into the WSL2 VM over 9p/drvfs with
    `uid=0;gid=0` and mode 0755; the images run as `acore` (uid 1000); so a
    container that must write `env/dist/etc` cannot, and `ac-db-import` fails
    with "cp: cannot create regular file ...: Permission denied" on files whose
    Windows ACLs give the user full control. Measured on a clean Windows 11 box
    (2026-08-25): the identical import exits 0 with this key and 1 without it.
    `DOCKER_USER=root`, which the image's own error text suggests, does nothing
    here - the generated compose sets no `user:` at all, so the image wins.

    Everywhere else this stays a comment, deliberately. On Linux, running as
    root makes every file the container creates root-owned ON THE HOST, which
    breaks the reason `env/dist/etc` is bound out in the first place: the module
    system and the user edit those files. Windows pays no such price because 9p
    maps ownership back to the Windows account regardless of the writing uid.
    """
    if platform_id() == "windows":
        return 'user: "0:0"'
    return "# user: left to the image (acore) - see composegen.container_user()"


def render(
    entry: CatalogEntry,
    server_dir: Path,
    *,
    templates_root: Path,
    world_env: Mapping[str, str] | None = None,
    db_password: str | None = None,
    bind_label: str = "",
    platform_id: Callable[[], str] = platform.detect,
) -> ComposePlan:
    """Render this entry's three compose files for an install in `server_dir`.

    `db_password` is the per-install value for a game whose plan is `generated`
    (the spine resolves it before stage 1); it may also override a fixed one. A
    fixed value is rendered into `docker-compose.yml` as the
    `${DB_ROOT_PASSWORD:-…}` default; a generated one goes only into the plan's
    `dotenv`, and a template that names `{{DB_PASSWORD}}` in that mode is
    refused.

    `bind_label` is appended to every `./…:` host bind in the templates:
    `":z"` when SELinux enforces and the filesystem can carry labels
    (`platform.bind_label()` decides; the spine passes it), otherwise empty, so
    off SELinux the rendered files are byte-identical to before 7.1. Never on a
    named volume — the templates put the token only on bind lines, and
    `test_composegen.py` counts them.

    Raises:
        ComposeGenError: the entry has no `install.native` block, a template is
            missing, a placeholder was left unfilled, a value cannot be safely
            spliced into YAML, the entry generates its password and none was
            given, a template names `{{DB_PASSWORD}}` in generated mode, or the
            entry declares `containers.services` (see `_container_prefix()`).
    """
    native = _native_of(entry)
    templates = templates_root / native.templates
    plan = entry.install.password
    if db_password is not None:
        password = db_password
    elif plan.mode == "fixed" and plan.value:
        password = plan.value
    else:
        raise ComposeGenError(
            f"{entry.name} generates its database password per install, and none was given "
            "to render its compose files with."
        )
    _refuse_unsafe(password, "the database root password")
    generated = plan.mode == "generated"
    template_names = ("base.yml.tmpl", "override.yml.tmpl", "build.yml.tmpl")
    texts = {name: _read_template(templates / name) for name in template_names}
    if generated:
        for name, text in texts.items():
            if "{{DB_PASSWORD}}" in text:
                raise ComposeGenError(
                    f"{{{{DB_PASSWORD}}}} appears in {templates / name}, but {entry.name} "
                    "generates its password per install; spell it "
                    "${DB_ROOT_PASSWORD:?Yu'lon .env is missing} so the secret stays in .env."
                )
    # An allow-list of two, because this value is spliced into a YAML list item
    # with no quoting at all: a newline in it writes whatever follows as another
    # mount, and the templates are the one place a stray mount would not be
    # noticed until a container had it.
    if bind_label not in ("", ":z"):
        raise ComposeGenError(
            f"the bind label {bind_label!r} is not a mount option this engine writes; "
            "only ':z' or nothing is spliced after a host bind."
        )
    tag = image_tag(server_dir, platform_id=platform_id)
    project = project_name(entry.id, server_dir, platform_id=platform_id)
    # The entry's own settings layered over the structural defaults, and an
    # explicit `world_env` overriding both — that is the seam a settings
    # surface arrives through.
    #
    # The `else {}` used to be a hole. An entry that said `family: "azerothcore"`
    # and omitted the `azerothcore` block validated, rendered here without
    # complaint, and handed the user mod-playerbots' OWN bot population instead
    # of the one that was decided — the same-button-different-world divergence
    # the 2026-08-24 `docker compose config` diff was run to catch, arriving
    # through a missing block rather than a missing key, and covered by nothing
    # because every test asserts against the shipped catalogue, which has the
    # block. `NativeInstall._exactly_the_family_block` (contract A14, added with
    # the CMaNGOS models) now closes it: no entry can reach this line saying
    # `azerothcore` without the block, so the branch is the honest default for
    # the `cmangos` family — which carries no `world_env`, because a CMaNGOS
    # server is configured through its `.conf` files and not through container
    # environment.
    env = _world_env(entry, world_env)
    base = fill(
        texts["base.yml.tmpl"],
        {
            "PROJECT_NAME": project,
            "DB_PORT": str(entry.ports.db or 3306),
            "AUTH_PORT": str(entry.ports.auth),
            "WORLD_PORT": str(entry.ports.world),
            "SOAP_PORT": str(native.soap_port),
            # Absent entirely in generated mode, so a template that names the
            # token fails `fill()`'s unfilled-placeholder check rather than
            # quietly rendering an empty password — belt to the refusal's
            # braces, which already caught it by name above.
            **({} if generated else {"DB_PASSWORD": password}),
            "IMAGE_PREFIX": native.image_prefix,
            "IMAGE_TAG": tag,
            "CONTAINER_USER": container_user(platform_id),
            "BIND_LABEL": bind_label,
            # The catalog facts (contract A6), last so the install-identity keys
            # above stay the authority on any name the two sets ever share. A
            # token no template uses costs nothing — `fill()` minds unfilled
            # placeholders, not unused values — so the WotLK files render byte
            # for byte as before (A16), and `MAKE_JOBS`/`CORE_DIR` are simply
            # absent for a non-`cmangos` entry rather than blank.
            **entry_tokens(entry),
        },
    )
    override = fill(
        texts["override.yml.tmpl"],
        {
            "ENVIRONMENT": _env_block(env),
            "BIND_LABEL": bind_label,
            "CHANNEL_SERVICE": _channel_service(entry, base, server_dir),
        },
    )
    build = fill(
        texts["build.yml.tmpl"],
        {
            # `.` and not the absolute path: the server dir IS the checkout, and
            # compose resolves a relative context against the file's own
            # directory, so a moved folder keeps building.
            "BUILD_CONTEXT": ".",
            # The catalog facts here too, for `CONTAINER_PREFIX`. A build block
            # is merged into the base file BY SERVICE NAME, and the shared
            # CMaNGOS overlay is one template for three games whose services
            # are `tbc-`, `vanilla-` and `tortoise-` prefixed, so it can only
            # spell its service key as a token. WotLK's overlay names its four
            # services in full and uses none of these — unused tokens cost
            # nothing (`fill()` minds unfilled placeholders, not unused
            # values), so its render stays byte-identical (A16).
            **entry_tokens(entry),
        },
    )
    return ComposePlan(base, override, build, {"DB_ROOT_PASSWORD": password} if generated else {})


def _read_template(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ComposeGenError(f"the compose template {path} could not be read: {exc}") from exc


def fill(text: str, tokens: Mapping[str, str]) -> str:
    """`{{TOKEN}}` substitution where an unresolved token is an ERROR.

    The ONE substitution for everything this engine renders — compose
    templates, a CMaNGOS Dockerfile, `.conf` values, SQL statements and the
    ready markers all come through here (contract A6), so a token spelled once
    in `catalog.json` means the same thing in every file. A template edit that
    adds a placeholder nobody fills would otherwise ship a compose file
    containing a literal `{{...}}`, which compose accepts happily as a string
    and which fails somewhere else entirely. Unused tokens are fine; unfilled
    ones are not.

    The refusal NAMES the token, and quotes nothing that was substituted. Every
    token is replaced before the leftover `{{` is looked for, so a window of the
    RESULT can hold a value that was filled in — on the shipped Tortoise
    statement `CREATE USER … IDENTIFIED BY '{{DB_PASSWORD}}'` that was eight
    characters of a constant prefix, and one shape over
    (`SELECT {{NOPE}} /*{{DB_PASSWORD}}*/`) it was the whole password, in a
    user-facing error whose tail invites the user to report it. The name is also
    the more useful message: `conf`, `sqlplan` and `native`'s ready markers all
    re-raise this text about a file the traceback never mentions.
    """
    out = text
    for key, value in tokens.items():
        out = out.replace("{{" + key + "}}", value)
    if "{{" in out:
        raise ComposeGenError(f"unfilled compose placeholder {_leftover(text, tokens)}")
    return out


_TOKEN = re.compile(r"\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}")


def _leftover(text: str, tokens: Mapping[str, str]) -> str:
    """Name the first `{{` the TEMPLATE spells that no token filled, without quoting a value.

    Read off the template rather than off the rendered text, which is the whole
    point: the template is data this repo ships and can be quoted freely, while
    the rendered text is where a secret has just been substituted.

    Three answers, because there are three ways a `{{` survives: a token nobody
    filled (named, the ordinary case); a `{{` the template never closes as a
    `{{TOKEN}}`, which is a typo in the template and is quoted as one; and a
    `{{` that arrived inside a filled VALUE, which is not the template's fault
    and is described rather than shown.
    """
    index = 0
    while (index := text.find("{{", index)) >= 0:
        filled = next((key for key in tokens if text.startswith("{{" + key + "}}", index)), None)
        if filled is not None:
            index += len(filled) + 4
            continue
        match = _TOKEN.match(text, index)
        if match is None:
            return (
                f"near {text[index:index + 40]!r} in the template, which is not a closed "
                "{{TOKEN}}"
            )
        return "{{" + match.group(1) + "}}"
    return "introduced by a filled value, not by the template"


_fill = fill
"""The pre-7.1 private name, kept so nothing that imported it moves twice."""


def _container_prefix(entry: CatalogEntry) -> str:
    """The part the three container names share: `ac-` for WotLK, `tbc-` for TBC.

    The shared CMaNGOS templates name services `{{CONTAINER_PREFIX}}db`,
    `..realmd`, `..mangosd` so they equal the entry's container names — the
    AzerothCore convention `docker.start_database()` relies on. Derived rather
    than declared, so the catalog cannot say two different things.

    Deriving it is right; deriving it with `os.path.commonprefix` and TRUSTING
    the answer was not. That function is character-wise, not separator- or
    token-aware, and it never raises: three names sharing no first character
    answer `""`, `db`/`dbauth`/`dbworld` answer `"db"` (so
    `{{CONTAINER_PREFIX}}db` renders `dbdb`), and `abc-db`/`abcd-realmd`/
    `abcx-mangosd` answer `"abc"`, with the separator eaten. Every one of those
    is a filled-but-wrong token, and `fill()` has no opinion about those — it
    refuses an UNFILLED placeholder — so the first thing to report it would be
    `docker compose up` naming a container no service owns. Two rules follow,
    and both are about what the catalog is ALLOWED to say, not about what the
    prefix happens to come out as:

    * an empty prefix is refused outright. It cannot be right for any entry.
    * `containers.services` is refused outright, whatever its value. This module
      writes the compose file, and the service keys in it are the templates' own
      — read 2026-09-04: `shared/cmangos/base.yml.tmpl` writes
      `{{CONTAINER_PREFIX}}db`/`realmd`/`mangosd`, `wow-wotlk/native/base.yml.tmpl`
      writes the literal `ac-database`/`ac-authserver`/`ac-worldserver` — so a
      declaration on the entry can only restate them or contradict them.

    What the refusal is allowed to say, measured 2026-09-04 on m910q (§30,
    round 2): the first rewrite of this rule refused the declaration and then
    named the entry's three container names as "the names compose must be
    given". With containers `db`/`dbauth`/`dbworld` the shared/cmangos
    templates rendered the keys `dbdb`/`dbrealmd`/`dbmangosd`, so every name in
    that advice answered `no such service` — the headline complaint of §30,
    reproduced by its fix. The suffix a template writes is not known here, so
    the refusal names no service at all; it says what to delete and where the
    names come from, and
    `test_the_refusal_names_no_service_the_rendered_file_does_not_define`
    renders the shape and holds the text to that.

    Until 2026-09-04 the second rule was the opposite: an entry declaring
    `containers.services` was accepted when the prefix rebuilt the container
    names from them, `container == prefix + service`. Probed on the shipped
    `wow-tbc` entry (bug-checklist §30) it answered backwards —

        ("tbc-db","tbc-realmd","tbc-mangosd")  -> REFUSED: 'tbc-' in front of
            those rebuilds tbc-tbc-db, tbc-tbc-realmd, tbc-tbc-mangosd
        ("db","realmd","mangosd")              -> ACCEPTED, prefix 'tbc-',
            and compose_services() then answered those three bare suffixes

    — so the one declaration shape it accepted was the one `docker compose up`
    answers `no such service` for, which is precisely the defect §26 fixed and
    the reason three CMaNGOS entries would have died at the first `up`. A rule
    satisfiable only by the bug it was written to refuse, whose refusal text
    ("Name every container after its service with one shared prefix in front of
    it") read as instructions for reproducing it, handed to whoever adds the
    fifth game.

    Correcting the rule to `service == container` was the other option and was
    rejected: it would accept a declaration that only ever restates what
    `ContainerSpec.compose_services()` already answers when the field is absent,
    and it leaves the next person a second place to write the two names apart.
    Refusing the declaration removes the opportunity instead of documenting it.
    `docker.ContainerSpec.services` itself stays — an ADOPTED project really can
    name its services and containers differently, which the integration suite's
    throwaway stack exercises on purpose — what has no correct value is the
    field on an entry whose compose file this module writes.

    The other two commonprefix shapes are not refused here, and cannot be:
    telling `dbdb` from `tbc-db` needs the literal suffix the template writes
    (`db`, `realmd`, `mangosd`), which lives in the template and not in the
    entry. Rendering first and then checking that every container name is a
    service key of the filled text was considered and rejected — the app has no
    YAML parser among its dependencies, the templates are data (style-guide §3),
    and a generation-time check that reads them would refuse every one-token
    template these tests render. Measured 2026-09-04 against the shipped
    `shared/cmangos` templates instead: containers `db`/`dbauth`/`dbworld` render
    the service keys `dbdb`/`dbrealmd`/`dbmangosd`, and `abc-db`/`abcd-realmd`/
    `abcx-mangosd` render `abcdb`/`abcrealmd`/`abcmangosd` — in neither case a
    name the entry would select, which is exactly the disagreement
    `test_every_service_the_catalog_selects_is_defined_in_the_rendered_compose_file`
    compares for every shipped entry, and
    `test_a_commonprefix_the_template_does_not_share_is_caught_by_the_rendered_file`
    pins on those two shapes. The price of catching it there rather than here,
    stated rather than glossed: a shipped entry fails the suite (that cross-check
    ran on all four shipped entries 2026-09-04), an entry added without running
    the suite fails at `compose up` after the build (the §26 Discord report of
    2026-08-26 is what that looks like).
    """
    services = entry.containers.services
    names = (entry.containers.db, entry.containers.auth, entry.containers.world)
    if services is not None:
        raise ComposeGenError(
            f"{entry.id} declares containers.services ({', '.join(services)}), but this engine "
            "generates the compose file and the service names in it come from the templates, "
            "not from the entry: no value of the field is both correct and needed. Delete "
            f"containers.services from {entry.id}. Whether its container names are then the "
            "services the rendered file defines is checked by rendering it, not here: "
            "test_every_service_the_catalog_selects_is_defined_in_the_rendered_compose_file."
        )
    prefix = os.path.commonprefix(list(names))
    if not prefix:
        raise ComposeGenError(
            f"the container names of {entry.id} ({', '.join(names)}) share no common prefix, "
            "so the container-prefix token would render the bare service names and the stack "
            "would name containers that no service owns. Give the three containers one shared "
            "prefix, as in <game>-db, <game>-realmd and <game>-mangosd."
        )
    return prefix


def entry_tokens(entry: CatalogEntry) -> dict[str, str]:
    """The per-game tokens every template, conf value and SQL statement may use.

    Facts the entry already states, spelled once: `DB_HOST` is the DB container
    (the conf files reach it by that name, not the scripts' bare `db`), the
    schema names are `databases.*`, and `LOGS_DB` is the first `extra` schema
    — omitted, not blanked, when there is none, so a template that wants it
    fails in `fill()` instead of writing `;;` into a conf. `MAKE_JOBS` and
    `CORE_DIR` exist only for a `cmangos` block: `CORE_DIR` is the core's
    in-image install prefix, derived as the parent of `conf.source_dir`
    (`/opt/mangos/etc` → `/opt/mangos`), which is where the binaries, the
    `etc/` bind and the `data/` bind all hang. `CmangosInstaller` adds the
    per-install ones on top of this mapping, in TWO sets since 7.3:
    `_public_tokens()` adds `REALM_HOST`, the three ports, the project name and
    the image prefix and tag, and is what the build context is rendered from;
    `_secret_tokens()` is that plus `DB_PASSWORD`, for the conf tables and
    (K.7) the SQL and verify.

    Raises:
        ComposeGenError: the entry has no `install.native` block, its three
            container names share no prefix, or it declares
            `containers.services` — the last two through `_container_prefix()`,
            which is reached from here and from nowhere else in the app.
    """
    native = _native_of(entry)
    tokens = {
        "DB_IMAGE": native.db.image,
        "DB_HOST": entry.containers.db,
        "DB_USER": native.db.user,
        "AUTH_DB": entry.databases.auth,
        "WORLD_DB": entry.databases.world,
        "CHAR_DB": entry.databases.characters,
        "CONTAINER_PREFIX": _container_prefix(entry),
        "CLIENT_BUILD": str(entry.client.build),
    }
    if entry.databases.extra:
        tokens["LOGS_DB"] = entry.databases.extra[0]
    if native.cmangos is not None:
        tokens["MAKE_JOBS"] = str(native.cmangos.dockerfile.make_jobs)
        tokens["CORE_DIR"] = str(PurePosixPath(native.cmangos.conf.source_dir).parent)
    return tokens


def _channel_service(entry: CatalogEntry, base: str, server_dir: Path) -> str:
    """The override's services block: the channel's published port, or nothing.

    Written here rather than in the template because the answer depends on the
    entry: WotLK's base file has published
    `${DOCKER_SOAP_EXTERNAL_PORT:-127.0.0.1:7878}:7878` since before there was a
    channel, so its entry says `publish: false` and this returns the empty
    mapping that keeps the file a valid compose document. The CMaNGOS trees
    publish no such port anywhere, so for them this is the only place it can
    come from (8.2c).

    The host side is pinned to loopback for the same reason 8.2a pins it: the
    listener binds every interface INSIDE the container, and nothing off this
    machine has business reaching a console that runs commands at SEC_CONSOLE.
    The variable name is the same contract the rollback uses to give the port
    back (`channel_setup.HOST_PORT_VAR`).
    """
    operations = entry.operations
    # `publish` is False for an attach channel and `port` is None on one -- that
    # core has no listener to publish. Both are checked, because the first is a
    # policy and the second is the fact behind it.
    if operations is None or not operations.publish or operations.port is None:
        return " {}"
    port = operations.port
    # `publish` is what the entry WANTS, not proof of what the install has
    # (adversarial review, 2026-09-07). Two things make the flag stale on a real
    # install: somebody editing the base file, and a later template revision
    # adding the binding while the flag stays. Compose concatenates ports lists,
    # so either would publish this container port twice -- the exact failure the
    # rule narrowed for this feature exists to prevent. So the answer comes from
    # the base file that will actually be loaded: the one on disk if there is
    # one, and otherwise the one being rendered beside this.
    installed = server_dir / BASE_FILE
    already = installed.read_text(encoding="utf-8") if installed.is_file() else base
    if _binds(already, port):
        logger.info(
            f"{entry.id}'s compose already publishes {port}; the override adds no second binding"
        )
        return " {}"
    return (
        f"\n  {entry.container_spec().world}:"
        f"\n    ports:"
        f'\n      - "${{DOCKER_SOAP_EXTERNAL_PORT:-127.0.0.1:{port}}}:{port}"'
    )


def _binds(compose_text: str, port: int) -> bool:
    """Whether this compose document publishes `port` on the container side.

    Reads the mappings under a `ports:` key rather than searching the text: the
    number appears in this file as an environment default and in comments too,
    and `"7878" in text` would answer yes to both.
    """
    inside = False
    indent = 0
    for line in compose_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        here = len(line) - len(line.lstrip())
        if stripped.rstrip(":") == "ports" and stripped.endswith(":"):
            inside, indent = True, here
            continue
        if inside and (not stripped.startswith("- ") or here <= indent):
            inside = False
        if inside and stripped.rstrip('"').rsplit(":", 1)[-1] == str(port):
            return True
    return False


def _env_block(env: Mapping[str, str]) -> str:
    """The override's `environment:` mapping, indented to sit under it.

    Values are double-quoted strings without exception. AzerothCore reads these
    as text, and YAML would otherwise turn `1` into an int and `on` into a
    boolean — a distinction compose passes through to the container as
    `AC_..=true`, which no `.conf` parser expects.
    """
    lines: list[str] = []
    for key in sorted(env):
        if not _is_env_identifier(key):
            raise ComposeGenError(f"{key!r} is not a usable environment variable name")
        _refuse_unsafe(env[key], f"the value of {key}")
        lines.append(f'      {key}: "{env[key]}"')
    return "\n".join(lines)


def _is_env_identifier(key: str) -> bool:
    return (
        bool(key)
        and (key[0].isalpha() or key[0] == "_")
        and all(char.isalnum() or char == "_" for char in key)
    )


def _refuse_unsafe(value: str, what: str) -> None:
    bad = sorted(set(value) & _UNSAFE_SCALAR_CHARS)
    if bad:
        raise ComposeGenError(
            f"{what} contains {' '.join(repr(char) for char in bad)}, which cannot be written "
            "into a compose file safely. Use letters, digits and simple punctuation."
        )


MARKER_BANNERS: tuple[str, ...] = (
    " — do not hand-edit; the install engine rewrites this file.",
    " — BUILD-ONLY overlay for the native install.",
    " — runtime settings for the native stack.",
)
"""Every shipped template's own continuation of `GENERATED_MARKER` on its first line,
verbatim, less the marker itself. `test_every_shipped_templates_first_line_is_ours`
reads every `.tmpl` file under `catalog/installers/` and checks its first line against
`is_marker_line()`, so a fourth banner -- or one of these three edited -- drifts this
constant out of sync loudly, in a test, rather than silently in production.

(T25 round 2) Round 1's fix was a SEPARATOR rule: the marker followed by a space and a
hyphen or em dash, whatever came after. The Codex review that followed found the hole
that left open -- `# generated by Yu'lon - my note`, a user's own aside using the same
punctuation this engine's own banners do, still read as ours and was replaced whole.
There is no per-install text on line one -- every render's first line comes verbatim from
a `.tmpl` file nobody's install ever edits -- so the set of lines this engine could ever
have written is not a shape to recognise, it is a short, finite list to enumerate.
"""


def is_marker_line(text: str) -> bool:
    """Is `text`'s first line one Yu'lon actually writes -- the marker alone, or with one
    of `MARKER_BANNERS` after it, exact?

    (T25) `startswith(GENERATED_MARKER)` was the original test, and it answered True for
    anything glued after the words: `# generated by Yu'lon-custom`, or a real banner's own
    punctuation reused for a private note (`# generated by Yu'lon - my note`) -- a user's
    own mark on a file they took over, sharing nothing with this engine but the words --
    read back as OURS and was replaced whole on the next write. A separator rule (round 1:
    the marker, a space, then any hyphen or em dash) closed the first shape and reopened
    the second, because it is still a SHAPE test where ownership is a question with a
    short, exact, enumerable answer: the marker on its own, or followed by exactly one of
    the sentences this project's own templates carry. Nothing else is a line this engine
    could have written.
    """
    line = text.split("\n", 1)[0].rstrip("\r")
    if line == GENERATED_MARKER:
        return True
    return any(line == GENERATED_MARKER + banner for banner in MARKER_BANNERS)


def is_ours(path: Path) -> bool:
    """Did this engine write the file at `path`? Missing counts as ours to write.

    The whole of the rewrite rule (see `GENERATED_MARKER`, `is_marker_line()`): only the
    first line is consulted, because that is the one place a marker cannot be introduced
    by accident, and an unreadable file answers False — the fail-closed answer
    for "should I overwrite this".
    """
    if not path.exists():
        return True
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            return is_marker_line(fh.readline())
    except OSError as exc:
        logger.warning(f"could not read {path} to see whether it is ours: {exc}")
        return False


_NAME_LINE = re.compile(r"^name:[ \t]*(\S+)[ \t]*$", re.MULTILINE)


def project_of(text: str) -> str | None:
    """The compose project a base file names on its top-level `name:` line, or None (T106).

    The project is where the install's character volume lives (`project_name()`), so
    this is the one line a repair must never change: a folder moved after install
    renders a different name, and writing it would start the server under a new
    project with an empty database volume beside the old one.
    """
    found = _NAME_LINE.search(text)
    return found.group(1) if found else None


class MixedBindLabels(ComposeGenError):
    """A compose file whose host binds disagree about `:z`: no install renders that (T106)."""


def bind_label_of(text: str) -> str | None:
    """The SELinux label a rendered compose file's host binds carry: `":z"`, `""` or None (T106).

    `":z"` when every `- ./` bind ends with it, `""` when none does, None when the
    text has no host bind at all. This is the install's own decision, read back
    off what it wrote, and a re-render must use it rather than ask the host again:
    asked while `getenforce` fails or the host is briefly permissive, the host
    says "no label", and a file written from that answer strips `:z` from an
    install whose containers then cannot read `./etc` once enforcing is back.

    The same rule as T102's `channel_setup._label_on_disk()` (branch
    `fix/t102-channel-selinux`, not merged when this was written), over text
    rather than a path; the two are meant to be folded into one.

    Raises:
        MixedBindLabels: some binds carry `:z` and some do not.
    """
    binds = [line.strip() for line in text.splitlines() if line.strip().startswith("- ./")]
    if not binds:
        return None
    labelled = [line.endswith(":z") for line in binds]
    if all(labelled):
        return ":z"
    if not any(labelled):
        return ""
    raise MixedBindLabels(
        "some of its host folders are labelled for SELinux (`:z`) and some are not, which is "
        "not how Yu'lon writes it"
    )


def _meaningful_lines(text: str) -> list[str]:
    return [
        line.rstrip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def same_compose(a: str, b: str) -> bool:
    """Do two compose texts say the same thing, whole-line comments and blank lines aside? (T106)

    The templates carry long comments that get reworded (T98's own review
    corrected two), and a reworded comment is no reason to ask a player to
    recreate a running server. Only whole-line comments are set aside: a trailing
    `# …` after a value is compared as written, which errs towards offering.
    A `#` line inside a block scalar is script text, not a YAML comment; the one
    such block the templates carry (T98's shell wrapper) has none, and a comment
    in a shell script would change nothing the script does either.
    """
    return _meaningful_lines(a) == _meaningful_lines(b)


def write_plan(
    plan: ComposePlan, server_dir: Path, *, replaceable: Sequence[str] = ()
) -> tuple[Path, ...]:
    """Write the three files (and merge `.env`), refusing to overwrite foreign ones.

    Returns the paths written, which is deliberately not always all three: a
    file whose content already matches is left alone so its mtime does not
    move, and an unchanged compose file is what tells a user's own `docker
    compose` that nothing needs recreating.

    `replaceable` names files the CALLER has separately proved may be
    overwritten despite carrying no marker, and it exists for exactly one file:
    `docker-compose.yml`, which the emulator repository ships at its own root.
    The server directory IS that checkout, so on every single install the clone
    stage lays an unmarked `docker-compose.yml` down before this runs, and the
    marker rule alone refused every install with "point the install at an empty
    folder" — told to a user who did, after a 2.4 GB clone (review,
    2026-08-23). This module cannot tell upstream's file from a real server's,
    so it does not guess; `native._generate_compose()` asks git whether the
    file is the tracked, unmodified one the clone wrote and passes the answer
    in. Nothing is replaceable by default.

    Raises:
        ComposeGenError: a compose file exists that this engine did not write
            and the caller did not name. Never deleted, never overwritten — the
            install stops instead, since the alternative is orphaning somebody's
            character volumes.
    """
    written: list[Path] = []
    for name, text in (
        (BASE_FILE, plan.base),
        (OVERRIDE_FILE, plan.override),
        (BUILD_FILE, plan.build),
    ):
        path = server_dir / name
        if name not in replaceable and not is_ours(path):
            raise ComposeGenError(
                f"{path} was not written by Yu'lon, so it was not touched and nothing was "
                "installed. Point the install at an empty folder, or move that file aside."
            )
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    if plan.dotenv:
        written.append(write_dotenv(server_dir, plan.dotenv))
    return tuple(written)


def merge_dotenv(existing: str, additions: Mapping[str, str]) -> str:
    """`.env` text with `additions` applied: existing assignments replaced, new ones appended.

    Reached through `write_plan()` for a generated-password game since 7.1; a
    fixed-password plan never fills `dotenv`, so WotLK never comes here.

    A merge and not a rewrite, because this file is shared. Compose interpolates
    the compose files from it, a later SOAP setup writes its own port binding
    into it, and the port-conflict remedy appends a `DOCKER_DB_EXTERNAL_PORT`
    — dropping a key nobody here recognises would silently undo one of those.

    An assignment is replaced in place so its position (and therefore which
    wins, since compose takes the LAST) does not change.
    """
    lines = existing.splitlines()
    remaining = dict(additions)
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].lstrip()
        key = stripped.split("=", 1)[0].strip() if "=" in stripped else ""
        if key in remaining:
            lines[index] = f"{key}={remaining.pop(key)}"
    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Written by Yu'lon's install engine.")
        lines += [f"{key}={remaining[key]}" for key in sorted(remaining)]
    return "\n".join(lines) + "\n"


def dotenv_value(server_dir: Path, key: str) -> str | None:
    """What `<server_dir>/.env` sets `key` to, or `None` when it does not set it.

    The LAST assignment, because that is the one compose takes; read with the
    same rules `merge_dotenv()` writes by (`export ` prefix, spaces around the
    key). A missing or unreadable file sets nothing.
    """
    try:
        text = (server_dir / DOTENV_FILE).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    found: str | None = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].lstrip()
        if "=" not in stripped:
            continue
        name, value = stripped.split("=", 1)
        if name.strip() == key:
            found = value.strip()
    return found


def write_dotenv(server_dir: Path, additions: Mapping[str, str]) -> Path:
    """Merge `additions` into `<server_dir>/.env`, atomically.

    Atomic and byte-preserving for the reason `docker.pin_project_name()` gives
    at length: this file can hold the database root password, and a truncating
    write interrupted by a full disk leaves a `.env` the user's database is no
    longer reachable through.
    """
    path = server_dir / DOTENV_FILE
    existing = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    merged = merge_dotenv(existing, additions)
    tmp = path.with_name(path.name + ".yulon-new")
    try:
        tmp.write_text(merged, encoding="utf-8", newline="\n")
        os.replace(tmp, path)  # atomic on POSIX and on Windows
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    return path
