"""Compose generation for the native install engine (roadmap 6.2).

One job: turn a catalog entry plus an install identity into the exact text of
three compose files and the keys that belong in `.env`. Pure functions, no
subprocess and no daemon, so the output can be asserted byte for byte — which
matters more here than anywhere else in the engine, because the first thing
that reports a wrong compose file is a build three hours later.

The *content* is template data under `catalog/installers/<game>/native/`
(style-guide §3), never a Python conditional. This module owns the identity,
the substitution, the refusal of anything that cannot be safely spliced, and
the merge into `.env`.

Why three files, restated where the code is:

* `docker-compose.yml` — `name:`, services, container names, image refs, ALL
  ports, binds, volumes, depends_on, healthchecks.
* `docker-compose.override.yml` — runtime `AC_*` env and the `./modules`
  mount, nothing structural: it is auto-loaded and it is rewritten by whatever
  settings surface comes next, whose YAML writer keeps only what it
  understands.
* `docker-compose.build.yml` — `build:` blocks only, never auto-loaded, so a
  post-install `up` cannot start a multi-hour rebuild.

**`ports:` appears in exactly one of them.** Compose CONCATENATES `ports:`
across files: a port "overridden" in the override publishes a second binding
rather than replacing the first. `test_composegen.py` asserts the rendered
override and build files carry no `ports:` key at any depth, and that test is
the only thing standing between a future edit and a stack that binds 3724
twice.
"""

from __future__ import annotations

import hashlib
import os
import re
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from yulon import platform
from yulon.catalog.catalog import CatalogEntry, NativeInstall
from yulon.log import get_logger

logger = get_logger(__name__)

BASE_FILE = "docker-compose.yml"
OVERRIDE_FILE = "docker-compose.override.yml"
BUILD_FILE = "docker-compose.build.yml"
DOTENV_FILE = ".env"

COMPOSE_FILES: tuple[str, ...] = (BASE_FILE, OVERRIDE_FILE, BUILD_FILE)
"""The `-f` set for every build, in order. See `docker.build_staged()`."""

GENERATED_MARKER = "# generated by Yu'lon"
"""First-line marker every generated file carries, and the whole of the rewrite rule.

`generate-compose` rewrites a file that begins with this and refuses to touch
one that does not. The incident it exists for is in `rust-prior-art.md` §1: a
state file dropped into a directory made the generator overwrite a real
server's compose file and orphan its character volumes. A marker means the
engine can only ever destroy its own work.
"""

INSTALL_ID_LENGTH = 8
"""Hex digits of the path hash that name an install. 8 is what `docker ps` can show.

A collision would give two installs one compose project — the bug this exists
to prevent — so the length is a real trade. 32 bits over the handful of
directories one person installs to is a birthday probability under 1e-8, and
the state file's own `install_id` check catches the pathological case at
install time rather than letting it run.
"""

# Runtime env the generated override starts with. Two keys, both load-bearing:
# without the first the one-shot never creates the playerbots schema, and
# without the second the bots never log in.
#
# The Linux installer's own override also pins AC_AI_PLAYERBOT_MIN/MAX_RANDOM_
# BOTS to 500/500, and this comment used to argue at length that they should
# stay out. They did not stay out — the compose diff against the proven install
# (2026-08-24) found that a native install would otherwise take mod-playerbots'
# defaults and hand the same user a different world from the same button, and
# they now ship in `catalog.json`'s `install.native.azerothcore.world_env`. Corrected after
# a sweep found this text still arguing the opposite of what the code does.
#
# The argument was not wrong, only outranked, and the part still worth keeping
# is the cost: an env key SHADOWS the matching row in playerbots.conf, so a
# settings surface that edits that file will appear to do nothing until this
# key is removed. Nor is rewriting the env itself immediate — a container that
# is already running keeps the population it started with until it is
# RECREATED, so anything that changes this number is changing what the next
# `up` builds, not what the world outside the window is doing. That is why the
# numbers are DATA in `catalog.json` and not a constant here — a per-game value
# a person may want different, style-guide §3. What is still unmeasured is
# whether 500 bots fits the laptop this path's preflight exists for; the first
# live gate owes an RSS reading at that population, and until it has one the
# number is decided, not earned.
DEFAULT_WORLD_ENV: Mapping[str, str] = {
    "AC_PLAYERBOTS_UPDATES_ENABLE_DATABASES": "1",
    "AC_AI_PLAYERBOT_RANDOM_BOT_AUTOLOGIN": "1",
}
"""Settings that are structural rather than tunable: without them the stack is wrong, not merely
different. Anything a person might reasonably want a different value for belongs in
`catalog.json`'s `install.native.azerothcore.world_env` instead — the playerbot population
started here and was moved there after an adversarial review pointed out that a per-game number
in a module constant is exactly what style-guide §3 forbids, and that one machine's bot
population is not a default for every machine.

The environment differences the compose diff turned up and this deliberately does NOT carry —
`AC_CCACHE`, `CTYPE`, `CSCRIPTS`, `DATAPATH`, `USER_CONF_PATH` and the three empty
`AC_RESTARTER_*` — are build-time settings upstream's compose file keeps on the runtime services
too. The image's `entrypoint.sh` reads none of them: it uses `CONF_DIR`, `LOGS_DIR` and
`ACORE_COMPONENT`, and the image sets `ACORE_COMPONENT` itself. Checked in the image, not assumed.
"""

# Characters that cannot be spliced into the templates safely, whatever the
# escaping. A scalar here lands in TWO contexts at once — a bare YAML value
# (`MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-<pw>}`) and a quoted, semicolon-
# separated one (`"ac-database;3306;root;<pw>;acore_auth"`) — and compose's own
# interpolation runs on top of both after YAML has already unescaped them. `#`
# truncates at a comment, `}` ends the `:-` default early, `;` splits the
# database field list, `"`/`\` break the quoted string, `$` opens another
# interpolation, and a newline splices arbitrary YAML. No single escaping
# survives all six, so a bad value is REFUSED: this is an install-time option
# and the user can pick another password.
_UNSAFE_SCALAR_CHARS = frozenset("$\"\\;#{}\r\n\t'")


class ComposeGenError(RuntimeError):
    """A compose file could not be generated (message is user-readable)."""


def install_id(server_dir: Path, *, platform_id: Callable[[], str] = platform.detect) -> str:
    """Short, stable id for one install, derived from where it lives.

    SHA-256 of the ABSOLUTE path, first `INSTALL_ID_LENGTH` hex digits. Three
    normalisations, each because two spellings of one directory must not become
    two stacks: the path is made absolute, back-slashes become forward slashes,
    and a trailing separator is dropped. On Windows it is also lowercased,
    because NTFS is case-insensitive and `C:\\Games\\wow` and `c:\\games\\wow`
    are the same folder.

    This is the value the compose project name carries and the value the state
    file records, which is what makes a COPIED install directory refusable:
    the copy's path hashes differently from the `install_id` its state file
    carries, so a resume in it is refused instead of adopting the original's
    containers and volumes.
    """
    return hashlib.sha256(_identity_key(server_dir, platform_id).encode()).hexdigest()[
        :INSTALL_ID_LENGTH
    ]


def _identity_key(server_dir: Path, platform_id: Callable[[], str]) -> str:
    text = str(Path(os.path.abspath(server_dir))).replace("\\", "/")
    while len(text) > 1 and text.endswith("/"):
        text = text[:-1]
    return text.lower() if platform_id() == "windows" else text


def project_name(
    game_id: str, server_dir: Path, *, platform_id: Callable[[], str] = platform.detect
) -> str:
    """This install's compose project: `yulon-<game>-<install id>`.

    Written into the base file's `name:`, which retires the `.env` pin on the
    native path entirely — `docker.compose_project_name()` already reads `name:`
    out of the files, so a moved folder keeps working because the identity
    travels inside it.

    Per-install rather than per-game because compose keys named VOLUMES by
    project too: two installs of one game under one project name would share a
    database volume, and the second `up` would mount the first's characters.
    """
    return f"yulon-{_slug(game_id)}-{install_id(server_dir, platform_id=platform_id)}"


def built_image_refs(
    entry: CatalogEntry, server_dir: Path, *, platform_id: Callable[[], str] = platform.detect
) -> tuple[str, ...]:
    """The image references this install's build produces, fully qualified.

    Needed because "has this been built?" cannot be asked of compose. Measured
    on yulon-ubuntu (Docker 29.1.3, Compose 2.40.3, 2026-08-24): after a
    successful `compose -f… build`, `compose images -q` returns **nothing** —
    both bare and with the same `-f` set — and only starts answering once
    containers exist (`compose create` is enough; `up` is not required). Compose
    enumerates the images of a project's CREATED CONTAINERS, not of its service
    definitions, exactly as `images_built()`'s docstring feared.

    That window — built, no containers yet — is the whole window a resume asks
    in, so the old question answered "not built" for every finished build and a
    resume re-ran the compile. Cheap in BuildKit cache terms and still wrong:
    the engine would have reported hours of work it did not need to do.

    The prefix and the service keys are the entry's (`install.native.images`,
    `.image_prefix`) since 7.1, so two games cannot tag into one namespace.
    """
    native = _native_of(entry)
    tag = image_tag(server_dir, platform_id=platform_id)
    return tuple(f"{native.image_prefix}{name}:{tag}" for name in native.images)


def _native_of(entry: CatalogEntry) -> NativeInstall:
    """The entry's native block, or the one refusal every native-only function shares."""
    if entry.install.native is None:
        raise ComposeGenError(
            f"{entry.name} does not say how to install natively (no `install.native` in "
            "catalog.json), so no compose files were generated."
        )
    return entry.install.native


def image_tag(server_dir: Path, *, platform_id: Callable[[], str] = platform.detect) -> str:
    """Default tag for images built for this install, so two builds cannot overwrite each other."""
    return f"native-{install_id(server_dir, platform_id=platform_id)}"


def _slug(text: str) -> str:
    """Lowercase `[a-z0-9_-]`, so the project name is legal and readable in `docker ps`."""
    out: list[str] = []
    for char in text.lower():
        if char.isascii() and (char.isalnum() or char in "-_"):
            out.append(char)
        elif out and out[-1] != "-":
            out.append("-")
    return "".join(out).strip("-_") or "game"


@dataclass(frozen=True)
class ComposePlan:
    """The three files' text plus the `.env` keys this install needs on top of them.

    `dotenv` is empty for a fixed-password game (WotLK): the catalog's value is
    the base file's interpolation default and needs no `.env`. For a
    generated-password game it carries exactly `DB_ROOT_PASSWORD`, which
    `write_plan()` merges into `.env` through `write_dotenv()` — the one writer
    of that file — so the secret is never in a compose file git can see. A
    docstring here once promised the second behaviour while nothing implemented
    it (review, 2026-08-23); it has had a caller since 7.1.
    """

    base: str
    override: str
    build: str
    dotenv: Mapping[str, str]


def container_user(platform_id: Callable[[], str] = platform.detect) -> str:
    """The `user:` line for the services that write to the bound-out env/dist.

    On Windows this is `user: "0:0"`, and it is not a convenience. Docker
    Desktop mounts a Windows drive into the WSL2 VM over 9p/drvfs with
    `uid=0;gid=0` and mode 0755; the images run as `acore` (uid 1000); so a
    container that must write `env/dist/etc` cannot, and `ac-db-import` fails
    with "cp: cannot create regular file ...: Permission denied" on files whose
    Windows ACLs give the user full control. Measured on a clean Windows 11 box
    (2026-08-25): the identical import exits 0 with this key and 1 without it.
    `DOCKER_USER=root`, which the image's own error text suggests, does nothing
    here - the generated compose sets no `user:` at all, so the image wins.

    Everywhere else this stays a comment, deliberately. On Linux, running as
    root makes every file the container creates root-owned ON THE HOST, which
    breaks the reason `env/dist/etc` is bound out in the first place: the module
    system and the user edit those files. Windows pays no such price because 9p
    maps ownership back to the Windows account regardless of the writing uid.
    """
    if platform_id() == "windows":
        return 'user: "0:0"'
    return "# user: left to the image (acore) - see composegen.container_user()"


def render(
    entry: CatalogEntry,
    server_dir: Path,
    *,
    templates_root: Path,
    world_env: Mapping[str, str] | None = None,
    db_password: str | None = None,
    bind_label: str = "",
    platform_id: Callable[[], str] = platform.detect,
) -> ComposePlan:
    """Render this entry's three compose files for an install in `server_dir`.

    `db_password` is the per-install value for a game whose plan is `generated`
    (the spine resolves it before stage 1); it may also override a fixed one. A
    fixed value is rendered into `docker-compose.yml` as the
    `${DB_ROOT_PASSWORD:-…}` default; a generated one goes only into the plan's
    `dotenv`, and a template that names `{{DB_PASSWORD}}` in that mode is
    refused.

    `bind_label` is appended to every `./…:` host bind in the templates:
    `":z"` when SELinux enforces and the filesystem can carry labels
    (`platform.bind_label()` decides; the spine passes it), otherwise empty, so
    off SELinux the rendered files are byte-identical to before 7.1. Never on a
    named volume — the templates put the token only on bind lines, and
    `test_composegen.py` counts them.

    Raises:
        ComposeGenError: the entry has no `install.native` block, a template is
            missing, a placeholder was left unfilled, a value cannot be safely
            spliced into YAML, the entry generates its password and none was
            given, a template names `{{DB_PASSWORD}}` in generated mode, or the
            entry declares `containers.services` (see `_container_prefix()`).
    """
    native = _native_of(entry)
    templates = templates_root / native.templates
    plan = entry.install.password
    if db_password is not None:
        password = db_password
    elif plan.mode == "fixed" and plan.value:
        password = plan.value
    else:
        raise ComposeGenError(
            f"{entry.name} generates its database password per install, and none was given "
            "to render its compose files with."
        )
    _refuse_unsafe(password, "the database root password")
    generated = plan.mode == "generated"
    template_names = ("base.yml.tmpl", "override.yml.tmpl", "build.yml.tmpl")
    texts = {name: _read_template(templates / name) for name in template_names}
    if generated:
        for name, text in texts.items():
            if "{{DB_PASSWORD}}" in text:
                raise ComposeGenError(
                    f"{{{{DB_PASSWORD}}}} appears in {templates / name}, but {entry.name} "
                    "generates its password per install; spell it "
                    "${DB_ROOT_PASSWORD:?Yu'lon .env is missing} so the secret stays in .env."
                )
    # An allow-list of two, because this value is spliced into a YAML list item
    # with no quoting at all: a newline in it writes whatever follows as another
    # mount, and the templates are the one place a stray mount would not be
    # noticed until a container had it.
    if bind_label not in ("", ":z"):
        raise ComposeGenError(
            f"the bind label {bind_label!r} is not a mount option this engine writes; "
            "only ':z' or nothing is spliced after a host bind."
        )
    tag = image_tag(server_dir, platform_id=platform_id)
    project = project_name(entry.id, server_dir, platform_id=platform_id)
    # The entry's own settings layered over the structural defaults, and an
    # explicit `world_env` overriding both — that is the seam a settings
    # surface arrives through.
    #
    # The `else {}` used to be a hole. An entry that said `family: "azerothcore"`
    # and omitted the `azerothcore` block validated, rendered here without
    # complaint, and handed the user mod-playerbots' OWN bot population instead
    # of the one that was decided — the same-button-different-world divergence
    # the 2026-08-24 `docker compose config` diff was run to catch, arriving
    # through a missing block rather than a missing key, and covered by nothing
    # because every test asserts against the shipped catalogue, which has the
    # block. `NativeInstall._exactly_the_family_block` (contract A14, added with
    # the CMaNGOS models) now closes it: no entry can reach this line saying
    # `azerothcore` without the block, so the branch is the honest default for
    # the `cmangos` family — which carries no `world_env`, because a CMaNGOS
    # server is configured through its `.conf` files and not through container
    # environment.
    entry_env = native.azerothcore.world_env if native.azerothcore is not None else {}
    env = dict(world_env) if world_env is not None else {**DEFAULT_WORLD_ENV, **entry_env}
    base = fill(
        texts["base.yml.tmpl"],
        {
            "PROJECT_NAME": project,
            "DB_PORT": str(entry.ports.db or 3306),
            "AUTH_PORT": str(entry.ports.auth),
            "WORLD_PORT": str(entry.ports.world),
            "SOAP_PORT": str(native.soap_port),
            # Absent entirely in generated mode, so a template that names the
            # token fails `fill()`'s unfilled-placeholder check rather than
            # quietly rendering an empty password — belt to the refusal's
            # braces, which already caught it by name above.
            **({} if generated else {"DB_PASSWORD": password}),
            "IMAGE_PREFIX": native.image_prefix,
            "IMAGE_TAG": tag,
            "CONTAINER_USER": container_user(platform_id),
            "BIND_LABEL": bind_label,
            # The catalog facts (contract A6), last so the install-identity keys
            # above stay the authority on any name the two sets ever share. A
            # token no template uses costs nothing — `fill()` minds unfilled
            # placeholders, not unused values — so the WotLK files render byte
            # for byte as before (A16), and `MAKE_JOBS`/`CORE_DIR` are simply
            # absent for a non-`cmangos` entry rather than blank.
            **entry_tokens(entry),
        },
    )
    override = fill(
        texts["override.yml.tmpl"],
        {"ENVIRONMENT": _env_block(env), "BIND_LABEL": bind_label},
    )
    build = fill(
        texts["build.yml.tmpl"],
        {
            # `.` and not the absolute path: the server dir IS the checkout, and
            # compose resolves a relative context against the file's own
            # directory, so a moved folder keeps building.
            "BUILD_CONTEXT": ".",
            # The catalog facts here too, for `CONTAINER_PREFIX`. A build block
            # is merged into the base file BY SERVICE NAME, and the shared
            # CMaNGOS overlay is one template for three games whose services
            # are `tbc-`, `vanilla-` and `tortoise-` prefixed, so it can only
            # spell its service key as a token. WotLK's overlay names its four
            # services in full and uses none of these — unused tokens cost
            # nothing (`fill()` minds unfilled placeholders, not unused
            # values), so its render stays byte-identical (A16).
            **entry_tokens(entry),
        },
    )
    return ComposePlan(base, override, build, {"DB_ROOT_PASSWORD": password} if generated else {})


def _read_template(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ComposeGenError(f"the compose template {path} could not be read: {exc}") from exc


def fill(text: str, tokens: Mapping[str, str]) -> str:
    """`{{TOKEN}}` substitution where an unresolved token is an ERROR.

    The ONE substitution for everything this engine renders — compose
    templates, a CMaNGOS Dockerfile, `.conf` values, SQL statements and the
    ready markers all come through here (contract A6), so a token spelled once
    in `catalog.json` means the same thing in every file. A template edit that
    adds a placeholder nobody fills would otherwise ship a compose file
    containing a literal `{{...}}`, which compose accepts happily as a string
    and which fails somewhere else entirely. Unused tokens are fine; unfilled
    ones are not.

    The refusal NAMES the token, and quotes nothing that was substituted. Every
    token is replaced before the leftover `{{` is looked for, so a window of the
    RESULT can hold a value that was filled in — on the shipped Tortoise
    statement `CREATE USER … IDENTIFIED BY '{{DB_PASSWORD}}'` that was eight
    characters of a constant prefix, and one shape over
    (`SELECT {{NOPE}} /*{{DB_PASSWORD}}*/`) it was the whole password, in a
    user-facing error whose tail invites the user to report it. The name is also
    the more useful message: `conf`, `sqlplan` and `native`'s ready markers all
    re-raise this text about a file the traceback never mentions.
    """
    out = text
    for key, value in tokens.items():
        out = out.replace("{{" + key + "}}", value)
    if "{{" in out:
        raise ComposeGenError(f"unfilled compose placeholder {_leftover(text, tokens)}")
    return out


_TOKEN = re.compile(r"\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}")


def _leftover(text: str, tokens: Mapping[str, str]) -> str:
    """Name the first `{{` the TEMPLATE spells that no token filled, without quoting a value.

    Read off the template rather than off the rendered text, which is the whole
    point: the template is data this repo ships and can be quoted freely, while
    the rendered text is where a secret has just been substituted.

    Three answers, because there are three ways a `{{` survives: a token nobody
    filled (named, the ordinary case); a `{{` the template never closes as a
    `{{TOKEN}}`, which is a typo in the template and is quoted as one; and a
    `{{` that arrived inside a filled VALUE, which is not the template's fault
    and is described rather than shown.
    """
    index = 0
    while (index := text.find("{{", index)) >= 0:
        filled = next((key for key in tokens if text.startswith("{{" + key + "}}", index)), None)
        if filled is not None:
            index += len(filled) + 4
            continue
        match = _TOKEN.match(text, index)
        if match is None:
            return (
                f"near {text[index:index + 40]!r} in the template, which is not a closed "
                "{{TOKEN}}"
            )
        return "{{" + match.group(1) + "}}"
    return "introduced by a filled value, not by the template"


_fill = fill
"""The pre-7.1 private name, kept so nothing that imported it moves twice."""


def _container_prefix(entry: CatalogEntry) -> str:
    """The part the three container names share: `ac-` for WotLK, `tbc-` for TBC.

    The shared CMaNGOS templates name services `{{CONTAINER_PREFIX}}db`,
    `..realmd`, `..mangosd` so they equal the entry's container names — the
    AzerothCore convention `docker.start_database()` relies on. Derived rather
    than declared, so the catalog cannot say two different things.

    Deriving it is right; deriving it with `os.path.commonprefix` and TRUSTING
    the answer was not. That function is character-wise, not separator- or
    token-aware, and it never raises: three names sharing no first character
    answer `""`, `db`/`dbauth`/`dbworld` answer `"db"` (so
    `{{CONTAINER_PREFIX}}db` renders `dbdb`), and `abc-db`/`abcd-realmd`/
    `abcx-mangosd` answer `"abc"`, with the separator eaten. Every one of those
    is a filled-but-wrong token, and `fill()` has no opinion about those — it
    refuses an UNFILLED placeholder — so the first thing to report it would be
    `docker compose up` naming a container no service owns. Two rules follow,
    and both are about what the catalog is ALLOWED to say, not about what the
    prefix happens to come out as:

    * an empty prefix is refused outright. It cannot be right for any entry.
    * `containers.services` is refused outright, whatever its value. This module
      writes the compose file, and the service keys in it are the templates' own
      — read 2026-09-04: `shared/cmangos/base.yml.tmpl` writes
      `{{CONTAINER_PREFIX}}db`/`realmd`/`mangosd`, `wow-wotlk/native/base.yml.tmpl`
      writes the literal `ac-database`/`ac-authserver`/`ac-worldserver` — so a
      declaration on the entry can only restate them or contradict them.

    What the refusal is allowed to say, measured 2026-09-04 on m910q (§30,
    round 2): the first rewrite of this rule refused the declaration and then
    named the entry's three container names as "the names compose must be
    given". With containers `db`/`dbauth`/`dbworld` the shared/cmangos
    templates rendered the keys `dbdb`/`dbrealmd`/`dbmangosd`, so every name in
    that advice answered `no such service` — the headline complaint of §30,
    reproduced by its fix. The suffix a template writes is not known here, so
    the refusal names no service at all; it says what to delete and where the
    names come from, and
    `test_the_refusal_names_no_service_the_rendered_file_does_not_define`
    renders the shape and holds the text to that.

    Until 2026-09-04 the second rule was the opposite: an entry declaring
    `containers.services` was accepted when the prefix rebuilt the container
    names from them, `container == prefix + service`. Probed on the shipped
    `wow-tbc` entry (bug-checklist §30) it answered backwards —

        ("tbc-db","tbc-realmd","tbc-mangosd")  -> REFUSED: 'tbc-' in front of
            those rebuilds tbc-tbc-db, tbc-tbc-realmd, tbc-tbc-mangosd
        ("db","realmd","mangosd")              -> ACCEPTED, prefix 'tbc-',
            and compose_services() then answered those three bare suffixes

    — so the one declaration shape it accepted was the one `docker compose up`
    answers `no such service` for, which is precisely the defect §26 fixed and
    the reason three CMaNGOS entries would have died at the first `up`. A rule
    satisfiable only by the bug it was written to refuse, whose refusal text
    ("Name every container after its service with one shared prefix in front of
    it") read as instructions for reproducing it, handed to whoever adds the
    fifth game.

    Correcting the rule to `service == container` was the other option and was
    rejected: it would accept a declaration that only ever restates what
    `ContainerSpec.compose_services()` already answers when the field is absent,
    and it leaves the next person a second place to write the two names apart.
    Refusing the declaration removes the opportunity instead of documenting it.
    `docker.ContainerSpec.services` itself stays — an ADOPTED project really can
    name its services and containers differently, which the integration suite's
    throwaway stack exercises on purpose — what has no correct value is the
    field on an entry whose compose file this module writes.

    The other two commonprefix shapes are not refused here, and cannot be:
    telling `dbdb` from `tbc-db` needs the literal suffix the template writes
    (`db`, `realmd`, `mangosd`), which lives in the template and not in the
    entry. Rendering first and then checking that every container name is a
    service key of the filled text was considered and rejected — the app has no
    YAML parser among its dependencies, the templates are data (style-guide §3),
    and a generation-time check that reads them would refuse every one-token
    template these tests render. Measured 2026-09-04 against the shipped
    `shared/cmangos` templates instead: containers `db`/`dbauth`/`dbworld` render
    the service keys `dbdb`/`dbrealmd`/`dbmangosd`, and `abc-db`/`abcd-realmd`/
    `abcx-mangosd` render `abcdb`/`abcrealmd`/`abcmangosd` — in neither case a
    name the entry would select, which is exactly the disagreement
    `test_every_service_the_catalog_selects_is_defined_in_the_rendered_compose_file`
    compares for every shipped entry, and
    `test_a_commonprefix_the_template_does_not_share_is_caught_by_the_rendered_file`
    pins on those two shapes. The price of catching it there rather than here,
    stated rather than glossed: a shipped entry fails the suite (that cross-check
    ran on all four shipped entries 2026-09-04), an entry added without running
    the suite fails at `compose up` after the build (the §26 Discord report of
    2026-08-26 is what that looks like).
    """
    services = entry.containers.services
    names = (entry.containers.db, entry.containers.auth, entry.containers.world)
    if services is not None:
        raise ComposeGenError(
            f"{entry.id} declares containers.services ({', '.join(services)}), but this engine "
            "generates the compose file and the service names in it come from the templates, "
            "not from the entry: no value of the field is both correct and needed. Delete "
            f"containers.services from {entry.id}. Whether its container names are then the "
            "services the rendered file defines is checked by rendering it, not here: "
            "test_every_service_the_catalog_selects_is_defined_in_the_rendered_compose_file."
        )
    prefix = os.path.commonprefix(list(names))
    if not prefix:
        raise ComposeGenError(
            f"the container names of {entry.id} ({', '.join(names)}) share no common prefix, "
            "so the container-prefix token would render the bare service names and the stack "
            "would name containers that no service owns. Give the three containers one shared "
            "prefix, as in <game>-db, <game>-realmd and <game>-mangosd."
        )
    return prefix


def entry_tokens(entry: CatalogEntry) -> dict[str, str]:
    """The per-game tokens every template, conf value and SQL statement may use.

    Facts the entry already states, spelled once: `DB_HOST` is the DB container
    (the conf files reach it by that name, not the scripts' bare `db`), the
    schema names are `databases.*`, and `LOGS_DB` is the first `extra` schema
    — omitted, not blanked, when there is none, so a template that wants it
    fails in `fill()` instead of writing `;;` into a conf. `MAKE_JOBS` and
    `CORE_DIR` exist only for a `cmangos` block: `CORE_DIR` is the core's
    in-image install prefix, derived as the parent of `conf.source_dir`
    (`/opt/mangos/etc` → `/opt/mangos`), which is where the binaries, the
    `etc/` bind and the `data/` bind all hang. `CmangosInstaller` adds the
    per-install ones on top of this mapping, in TWO sets since 7.3:
    `_public_tokens()` adds `REALM_HOST`, the three ports, the project name and
    the image prefix and tag, and is what the build context is rendered from;
    `_secret_tokens()` is that plus `DB_PASSWORD`, for the conf tables and
    (K.7) the SQL and verify.

    Raises:
        ComposeGenError: the entry has no `install.native` block, its three
            container names share no prefix, or it declares
            `containers.services` — the last two through `_container_prefix()`,
            which is reached from here and from nowhere else in the app.
    """
    native = _native_of(entry)
    tokens = {
        "DB_IMAGE": native.db.image,
        "DB_HOST": entry.containers.db,
        "DB_USER": native.db.user,
        "AUTH_DB": entry.databases.auth,
        "WORLD_DB": entry.databases.world,
        "CHAR_DB": entry.databases.characters,
        "CONTAINER_PREFIX": _container_prefix(entry),
        "CLIENT_BUILD": str(entry.client.build),
    }
    if entry.databases.extra:
        tokens["LOGS_DB"] = entry.databases.extra[0]
    if native.cmangos is not None:
        tokens["MAKE_JOBS"] = str(native.cmangos.dockerfile.make_jobs)
        tokens["CORE_DIR"] = str(PurePosixPath(native.cmangos.conf.source_dir).parent)
    return tokens


def _env_block(env: Mapping[str, str]) -> str:
    """The override's `environment:` mapping, indented to sit under it.

    Values are double-quoted strings without exception. AzerothCore reads these
    as text, and YAML would otherwise turn `1` into an int and `on` into a
    boolean — a distinction compose passes through to the container as
    `AC_..=true`, which no `.conf` parser expects.
    """
    lines: list[str] = []
    for key in sorted(env):
        if not _is_env_identifier(key):
            raise ComposeGenError(f"{key!r} is not a usable environment variable name")
        _refuse_unsafe(env[key], f"the value of {key}")
        lines.append(f'      {key}: "{env[key]}"')
    return "\n".join(lines)


def _is_env_identifier(key: str) -> bool:
    return (
        bool(key)
        and (key[0].isalpha() or key[0] == "_")
        and all(char.isalnum() or char == "_" for char in key)
    )


def _refuse_unsafe(value: str, what: str) -> None:
    bad = sorted(set(value) & _UNSAFE_SCALAR_CHARS)
    if bad:
        raise ComposeGenError(
            f"{what} contains {' '.join(repr(char) for char in bad)}, which cannot be written "
            "into a compose file safely. Use letters, digits and simple punctuation."
        )


def is_ours(path: Path) -> bool:
    """Did this engine write the file at `path`? Missing counts as ours to write.

    The whole of the rewrite rule (see `GENERATED_MARKER`): only the first line
    is consulted, because that is the one place a marker cannot be introduced
    by accident, and an unreadable file answers False — the fail-closed answer
    for "should I overwrite this".
    """
    if not path.exists():
        return True
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            return fh.readline().startswith(GENERATED_MARKER)
    except OSError as exc:
        logger.warning(f"could not read {path} to see whether it is ours: {exc}")
        return False


def write_plan(
    plan: ComposePlan, server_dir: Path, *, replaceable: Sequence[str] = ()
) -> tuple[Path, ...]:
    """Write the three files (and merge `.env`), refusing to overwrite foreign ones.

    Returns the paths written, which is deliberately not always all three: a
    file whose content already matches is left alone so its mtime does not
    move, and an unchanged compose file is what tells a user's own `docker
    compose` that nothing needs recreating.

    `replaceable` names files the CALLER has separately proved may be
    overwritten despite carrying no marker, and it exists for exactly one file:
    `docker-compose.yml`, which the emulator repository ships at its own root.
    The server directory IS that checkout, so on every single install the clone
    stage lays an unmarked `docker-compose.yml` down before this runs, and the
    marker rule alone refused every install with "point the install at an empty
    folder" — told to a user who did, after a 2.4 GB clone (review,
    2026-08-23). This module cannot tell upstream's file from a real server's,
    so it does not guess; `native._generate_compose()` asks git whether the
    file is the tracked, unmodified one the clone wrote and passes the answer
    in. Nothing is replaceable by default.

    Raises:
        ComposeGenError: a compose file exists that this engine did not write
            and the caller did not name. Never deleted, never overwritten — the
            install stops instead, since the alternative is orphaning somebody's
            character volumes.
    """
    written: list[Path] = []
    for name, text in (
        (BASE_FILE, plan.base),
        (OVERRIDE_FILE, plan.override),
        (BUILD_FILE, plan.build),
    ):
        path = server_dir / name
        if name not in replaceable and not is_ours(path):
            raise ComposeGenError(
                f"{path} was not written by Yu'lon, so it was not touched and nothing was "
                "installed. Point the install at an empty folder, or move that file aside."
            )
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    if plan.dotenv:
        written.append(write_dotenv(server_dir, plan.dotenv))
    return tuple(written)


def merge_dotenv(existing: str, additions: Mapping[str, str]) -> str:
    """`.env` text with `additions` applied: existing assignments replaced, new ones appended.

    Reached through `write_plan()` for a generated-password game since 7.1; a
    fixed-password plan never fills `dotenv`, so WotLK never comes here.

    A merge and not a rewrite, because this file is shared. Compose interpolates
    the compose files from it, a later SOAP setup writes its own port binding
    into it, and the port-conflict remedy appends a `DOCKER_DB_EXTERNAL_PORT`
    — dropping a key nobody here recognises would silently undo one of those.

    An assignment is replaced in place so its position (and therefore which
    wins, since compose takes the LAST) does not change.
    """
    lines = existing.splitlines()
    remaining = dict(additions)
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].lstrip()
        key = stripped.split("=", 1)[0].strip() if "=" in stripped else ""
        if key in remaining:
            lines[index] = f"{key}={remaining.pop(key)}"
    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Written by Yu'lon's install engine.")
        lines += [f"{key}={remaining[key]}" for key in sorted(remaining)]
    return "\n".join(lines) + "\n"


def write_dotenv(server_dir: Path, additions: Mapping[str, str]) -> Path:
    """Merge `additions` into `<server_dir>/.env`, atomically.

    Atomic and byte-preserving for the reason `docker.pin_project_name()` gives
    at length: this file can hold the database root password, and a truncating
    write interrupted by a full disk leaves a `.env` the user's database is no
    longer reachable through.
    """
    path = server_dir / DOTENV_FILE
    existing = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
    merged = merge_dotenv(existing, additions)
    tmp = path.with_name(path.name + ".yulon-new")
    try:
        tmp.write_text(merged, encoding="utf-8", newline="\n")
        os.replace(tmp, path)  # atomic on POSIX and on Windows
    except OSError:
        tmp.unlink(missing_ok=True)
        raise
    return path
