// GENERATED from crates/dml-wow/data/unbound-addons/ -- see unbound_addons.rs.
// 43 files. Regenerate only together with a deliberate re-extraction of
// WrathUnbound-Addons.zip, and move the fingerprint pin with it.
pub const ADDON_FILES: &[AddonFile] = &[
    addon!("UnboundSpellbook/ClassData.lua"),
    addon!("UnboundSpellbook/Core.lua"),
    addon!("UnboundSpellbook/DATABASE_COUNTS.txt"),
    addon!("UnboundSpellbook/DATA_CREDITS.txt"),
    addon!("UnboundSpellbook/README.txt"),
    addon!("UnboundSpellbook/UI.lua"),
    addon!("UnboundSpellbook/UnboundSpellbook.toc"),
    addon!("multiclass-resources/multiclass-resources.lua"),
    addon!("multiclass-resources/multiclass-resources.toc"),
    addon!("multiclass-talents-ui/Art/!UI-Frame.blp"),
    addon!("multiclass-talents-ui/Art/UI-Background-Marble.blp"),
    addon!("multiclass-talents-ui/Art/UI-Background-Rock.blp"),
    addon!("multiclass-talents-ui/Art/UI-Frame.blp"),
    addon!("multiclass-talents-ui/Art/_UI-Frame.blp"),
    addon!("multiclass-talents-ui/Core.lua"),
    addon!("multiclass-talents-ui/Data/AllSpells.lua"),
    addon!("multiclass-talents-ui/Data/Constants.lua"),
    addon!("multiclass-talents-ui/Data/Morphs.lua"),
    addon!("multiclass-talents-ui/Data/Racials.lua"),
    addon!("multiclass-talents-ui/Data/TalentData.lua"),
    addon!("multiclass-talents-ui/Data/Talents_DeathKnight.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Druid.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Hunter.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Mage.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Paladin.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Priest.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Rogue.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Shaman.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Warlock.lua"),
    addon!("multiclass-talents-ui/Data/Talents_Warrior.lua"),
    addon!("multiclass-talents-ui/Integration.lua"),
    addon!("multiclass-talents-ui/UI/CenterPanel.lua"),
    addon!("multiclass-talents-ui/UI/ClassTab.lua"),
    addon!("multiclass-talents-ui/UI/Helpers.lua"),
    addon!("multiclass-talents-ui/UI/Layout.lua"),
    addon!("multiclass-talents-ui/UI/MainFrame.lua"),
    addon!("multiclass-talents-ui/UI/SearchSidebar.lua"),
    addon!("multiclass-talents-ui/UI/SpecPanel.lua"),
    addon!("multiclass-talents-ui/UI/SpecTabBar.lua"),
    addon!("multiclass-talents-ui/UI/SpellGridPanel.lua"),
    addon!("multiclass-talents-ui/UI/TalentButton.lua"),
    addon!("multiclass-talents-ui/UI/TopTabBar.lua"),
    addon!("multiclass-talents-ui/multiclass-talents-ui.toc"),];
