#!/usr/bin/env bash
# Put m910q's Tortoise back exactly as it was before tortoise-reimport-live.sh: the pre-rebuild
# image on the tag compose expects, tw_world from today's dump, the two character-side changes
# undone (the unique index their 0903 migration makes, and its row), Dockerfile back to 22.04.
set -u
LOG="/c/Users/perzi/AppData/Local/Temp/claude/C--Users-perzi-dads-mmo-lab/e6db1900-f1cd-4099-995e-e1ef6bec1004/scratchpad/tortoise-rollback.log"
say() { echo "[$(date -u +%H:%M:%SZ)] $*" | tee -a "$LOG"; }
onbox() { ssh m910q "$1" 2>&1 | tee -a "$LOG"; }
say "=========== TORTOISE ROLLBACK (m910q) ==========="
onbox 'claude-say "Yulon: rolling Tortoise back to the pre-rebuild image and today dumps" >/dev/null 2>&1; cd ~/tortoise-server && sudo docker compose stop >/dev/null 2>&1; sudo docker tag yulon.local/cmangos-tortoise-server:rollback-2026-09-08 yulon.local/cmangos-tortoise-server:native-58c6fd1c && sed -i "s|^FROM ubuntu:24.04|FROM ubuntu:22.04|" Dockerfile && sudo docker compose up -d tortoise-db >/dev/null 2>&1 && for i in $(seq 1 40); do s=$(sudo docker inspect tortoise-db --format "{{.State.Health.Status}}" 2>/dev/null); [ "$s" = healthy ] && break; sleep 3; done; echo "db: $s"; PW=$(cat .db_password); M="sudo docker exec -i -e MYSQL_PWD=$PW tortoise-db mariadb -u root"; $M -e "DROP DATABASE IF EXISTS tw_world; CREATE DATABASE tw_world DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" && $M tw_world < ~/tortoise-backup-2026-09-08b/tw_world.sql && echo "tw_world restored from the dump"; $M -e "ALTER TABLE tw_char.ai_playerbot_random_bots DROP INDEX IF EXISTS uq_owner_bot_event; ALTER TABLE tw_char.ai_playerbot_random_bots ADD INDEX IF NOT EXISTS idx_owner_bot_event (owner, bot, event); DELETE FROM tw_char.migrations WHERE Name LIKE '"'"'20260903211500%'"'"'; DROP TABLE IF EXISTS tw_char.character_pvp_currency;" && echo "tw_char side undone"; $M -N -e "SELECT COUNT(*) FROM tw_world.migrations; SELECT COUNT(*) FROM tw_char.migrations; SELECT COUNT(*) FROM tw_char.characters" | tr "\n" " "; echo " (world migrations, char migrations, characters) -- compare counts-before.txt: $(cat ~/tortoise-backup-2026-09-08b/counts-before.txt)"; sudo docker compose up -d >/dev/null 2>&1; for i in $(seq 1 40); do sleep 10; L=$(sudo docker logs tortoise-mangosd 2>&1); echo "$L" | grep -q -E "World server is up and running|World initialized|Ready to login" && { echo "old build UP"; break; }; echo "$L" | grep -q "AutoUpdater FAILED" && { echo "old build FAILED to start"; break; }; done; sudo docker compose stop >/dev/null 2>&1; echo "stopped"'
say DONE
